#!/bin/sh
set -e

case "$1" in
  configure)
    if command -v systemctl >/dev/null 2>&1; then
      systemctl daemon-reload || true
      systemctl enable --now rs-linux-exporter.service || true
    fi
    ;;
esac

exit 0
